"""add completion fields

Revision ID: 793408a0717b
Revises: 
Create Date: 2026-04-24 21:35:09.843546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793408a0717b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('certificate_id', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint('uq_cert_id', ['certificate_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_cert_id', type_='unique')
        batch_op.drop_column('certificate_id')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('is_completed')

    # ### end Alembic commands ###